export interface Car {
    id: number,
    brand: string,
    model: string,
    km: string,
    year: string,
    shift: string,
    fuel: string,
    color: string,
    car_type: string,
    e_car: boolean,
    damages?:[]
}

export const Brands: Array<string> = [
    "Mercury",
    "Hyundai",
    "Lexus",
    "Chevrolet",
    "Oldsmobile",
    "GMC",
    "Mercedes-Benz",
    "Cadillac",
    "Volkswagen",
    "Toyota",
    "Dodge",
    "Lincoln",
    "Subaru",
    "Ford",
    "Saab",
    "Audi",
    "Aston Martin",
    "Mazda",
    "Suzuki",
    "Jeep",
    "Acura",
    "BMW",
    "Kia",
    "Maybach",
    "Mitsubishi",
    "Buick",
    "Chrysler",
    "Daewoo",
    "Geo",
    "Volvo",
    "Plymouth",
    "Lotus",
    "Nissan",
    "Bentley",
    "Pontiac",
    "Honda",
    "Porsche",
    "Lamborghini",
    "Eagle",
    "Jaguar",
    "Daihatsu",
    "Isuzu",
    "Ram",
    "Maserati",
    "Infiniti",
    "Tesla",
    "Ferrari",
    "MINI",
    "Land Rover",
    "Spyker",
    "Morgan",
    "Hillman",
    "Holden",
    "Shelby",
    "Saturn",
    "Scion",
    "Hummer",
    "Citroën",
    "Panoz"
];

export const Models: Array<string> = [
    "Lynx",
    "Scoupe",
    "LS",
    "Corvette",
    "Alero",
    "Sonoma",
    "SC",
    "G-Class",
    "Escalade",
    "Jetta",
    "4Runner",
    "Daytona",
    "Tracer",
    "Mark VIII",
    "Forester",
    "Justy",
    "GTI",
    "Ranger",
    "R-Class",
    "Accent",
    "900",
    "Explorer",
    "Express 1500",
    "LUV",
    "A8",
    "F350",
    "Rapide",
    "B-Series Plus",
    "Reno",
    "Seville",
    "Fusion",
    "Town Car",
    "Coupe GT",
    "Ciera",
    "Cobalt",
    "Xtra",
    "Commander",
    "Astro",
    "MDX",
    "Sierra 3500",
    "rio",
    "7 Series",
    "Azera",
    "E-Class",
    "Silhouette",
    "Passat",
    "F150",
    "Baja",
    "Venza",
    "CLK-Class",
    "Ram Van 3500",
    "Cutlass",
    "ZDX",
    "Sedona",
    "Tacoma",
    "57",
    "Endeavor",
    "3 Series",
    "Soul",
    "Fox",
    "Dakota",
    "F-250 Super Duty",
    "Suburban 1500",
    "Golf",
    "Lucerne",
    "Concorde",
    "Lanos",
    "Celica",
    "Continental",
    "Prizm",
    "XC70",
    "Impreza",
    "Breeze",
    "Highlander",
    "LX",
    "Evora",
    "Ram Van 1500",
    "Durango",
    "Tribute",
    "Ram 1500 Club",
    "ES",
    "Explorer Sport Trac",
    "Imperial",
    "Crown Victoria",
    "Cabriolet",
    "Maxima",
    "Continental Flying Spur",
    "Bravada",
    "Lancer",
    "Elise",
    "Avalon",
    "Cherokee",
    "M5",
    "Z3",
    "Cougar",
    "S60",
    "Torrent",
    "525",
    "Cirrus",
    "C30",
    "TL",
    "Century",
    "A6",
    "GTO",
    "Mustang",
    "Camry",
    "SRX",
    "Econoline E150",
    "Compass",
    "Club Wagon",
    "Wrangler",
    "Civic",
    "Daewoo Lacetti",
    "Sonata",
    "Galant",
    "Grand Prix Turbo",
    "Exige",
    "MR2",
    "F450",
    "Fit",
    "Grand Voyager",
    "F-Series",
    "Navigator",
    "Firebird",
    "Cayman",
    "Murciélago LP640",
    "Tracker",
    "Odyssey",
    "Armada",
    "RAV4",
    "Avenger",
    "E250",
    "Corolla",
    "Talon",
    "SVX",
    "Classic",
    "Sportvan G20",
    "Acclaim",
    "Regal",
    "Avalanche",
    "Integra",
    "1500 Club Coupe",
    "Genesis Coupe",
    "V70",
    "D250 Club",
    "E150",
    "Caravan",
    "XL-7",
    "62",
    "MX-5",
    "CX-9",
    "929",
    "3500",
    "Azure",
    "Mountaineer",
    "XF",
    "CX-7",
    "Envoy XUV",
    "Xterra",
    "Town & Country",
    "Aviator",
    "944",
    "3000GT",
    "Yukon XL 2500",
    "Tercel",
    "Rocky",
    "Eurovan",
    "Ram 2500",
    "Amigo",
    "Acadia",
    "Starion",
    "Canyon",
    "XC90",
    "Taurus",
    "S-Class",
    "Intrepid",
    "Eldorado",
    "911",
    "Lancer Evolution",
    "B-Series",
    "Diamante",
    "Prius",
    "Elantra",
    "Elan",
    "Excursion",
    "Karif",
    "Sportvan G10",
    "Eclipse",
    "Grand Cherokee",
    "Stylus",
    "Yukon",
    "SL-Class",
    "Laser",
    "9-5",
    "Esprit",
    "Eos",
    "Rally Wagon 1500",
    "RL",
    "Sportage",
    "Tempo",
    "I",
    "Park Avenue",
    "Vanquish S",
    "Savana 3500",
    "PT Cruiser",
    "Topaz",
    "LeMans",
    "Model S",
    "3500 Club Coupe",
    "Rio",
    "LTD",
    "Grand Caravan",
    "Monte Carlo",
    "Tiburon",
    "riolet",
    "Diablo",
    "Amanti",
    "L300",
    "928",
    "Econoline E250",
    "M",
    "Envoy",
    "Cavalier",
    "M-Class",
    "Savana 2500",
    "Ram 3500",
    "Impala",
    "Q",
    "Matrix",
    "9-3",
    "Grand Am",
    "Sonoma Club",
    "Savana 1500",
    "530",
    "599 GTB Fiorano",
    "Legacy",
    "RSX",
    "Mazda5",
    "5 Series",
    "NSX",
    "RX-7",
    "240SX",
    "E-Series",
    "Marquis",
    "Altima",
    "Aveo",
    "EV1",
    "Sidekick",
    "Quattroporte",
    "924 S",
    "Lumina",
    "Countryman",
    "Mirage",
    "Precis",
    "Defender",
    "S-Type",
    "Continental GTC",
    "Sienna",
    "Leone",
    "Contour",
    "XLR",
    "Firefly",
    "FF",
    "Challenger",
    "Cooper",
    "626",
    "Raider",
    "Venture",
    "Sequoia",
    "Accord",
    "Voyager",
    "Swift",
    "Silverado 2500",
    "645",
    "Bonneville",
    "Clubman",
    "Impreza WRX",
    "GS",
    "CL-Class",
    "Beretta",
    "Escort",
    "S8",
    "X-Type",
    "JUKE",
    "IS",
    "Edge",
    "Ridgeline",
    "Versa",
    "Outlander",
    "C8",
    "G-Series G20",
    "400E",
    "Verano",
    "Expedition",
    "Z4 M",
    "Sunbird",
    "MX-6",
    "Pathfinder",
    "SLS AMG",
    "Cayenne",
    "JX",
    "Touareg",
    "X5",
    "Aero 8",
    "Legend",
    "Equinox",
    "A4",
    "Rainier",
    "940",
    "Express 3500",
    "G",
    "Arnage",
    "Electra",
    "1500",
    "430",
    "Neon",
    "Rodeo",
    "Brooklands",
    "Vandura 3500",
    "S40",
    "Minx Magnificent",
    "VS Commodore",
    "Silverado 3500HD",
    "Aries",
    "Savana",
    "Tempest",
    "GX",
    "Aztek",
    "Aurora",
    "Jimmy",
    "Econoline E350",
    "Sprinter",
    "Silverado 3500",
    "Hombre",
    "Montero",
    "Z8",
    "Sorento",
    "Tundra",
    "Millenia",
    "Tiguan",
    "Suburban 2500",
    "300ZX",
    "Liberty",
    "Spectra",
    "Mark LT",
    "GT350",
    "Vibe",
    "200",
    "MKX",
    "Sephia",
    "Expo LRV",
    "100",
    "EX",
    "Cutlass Supreme",
    "Relay",
    "MPV",
    "SJ 410",
    "Tredia",
    "Esprit Turbo",
    "Sunfire",
    "i-Series",
    "Optima",
    "Quest",
    "Sebring",
    "Crossfire",
    "612 Scaglietti",
    "Tacoma Xtra",
    "300D",
    "Vitara",
    "Corsica",
    "Catera",
    "L-Series",
    "FR-S",
    "H2",
    "STS",
    "Countach",
    "740",
    "Q7",
    "F250",
    "C70",
    "S4",
    "CTS",
    "Monterey",
    "Grand Prix",
    "SLK-Class",
    "QX",
    "Riviera",
    "TT",
    "Freestyle",
    "New Beetle",
    "XK Series",
    "G37",
    "Rodeo Sport",
    "MKS",
    "Jetta III",
    "323",
    "Rogue",
    "Malibu",
    "Silverado 1500",
    "Equator",
    "6 Series",
    "Navajo",
    "Virage",
    "T100 Xtra",
    "X3",
    "RS 4",
    "Journey",
    "Suburban",
    "California",
    "Outback",
    "Vandura 1500",
    "Alpina B7",
    "Civic Si",
    "Space",
    "Camaro",
    "LTD Crown Victoria",
    "J",
    "DeVille",
    "Windstar",
    "M6",
    "98",
    "Boxster",
    "IS F",
    "RX",
    "Allante",
    "GLI",
    "Ram 1500",
    "B9 Tribeca",
    "325",
    "FX",
    "B2600",
    "850",
    "Escape",
    "350Z",
    "VUE",
    "GT500",
    "RX Hybrid",
    "Capri",
    "Discovery",
    "SM",
    "Festiva",
    "Cutlass Cruiser",
    "C8 Spyder",
    "X6 M",
    "D350 Club",
    "XG350",
    "Chariot",
    "Murano",
    "Frontier",
    "XJ",
    "Roadmaster",
    "Esteem",
    "228",
    "tC",
    "Oasis",
    "Escalade ESV",
    "XT",
    "Range Rover",
    "Escalade EXT",
    "300",
    "Panamera",
    "Express 2500",
    "Familia",
    "Ion",
    "Forte",
    "Yukon XL 1500",
    "Skyhawk",
    "Safari",
    "Caliber",
    "G-Series 3500",
    "Aerostar",
    "CLS-Class",
    "Expedition EL",
    "V40",
    "Montero Sport",
    "Verona",
    "S6",
    "Paseo",
    "Focus",
    "Truck",
    "Skylark",
    "Solara",
    "Fleetwood",
    "Axiom",
    "Caprice",
    "Tahoe",
    "Esperante",
    "Probe",
    "1 Series",
    "Gallardo",
    "Trooper",
    "Aspen",
    "Passport",
    "430 Scuderia",
    "Fiero",
    "Datsun/Nissan Z-car",
    "D150",
    "88"
];

export const Fuels: Array<string> = [
    "Petrol",
    "Diesel",
    "Benzin",
    "CNG",
    "Propane"
];

export const CarType: Array<string> = [
    'Automatic',
    'Manual'
];

export const Color: Array<string> = [
    "Violet",
    "Teal",
    "Indigo",
    "Goldenrod",
    "Fuscia",
    "Orange",
    "Maroon",
    "Red",
    "Puce",
    "Turquoise",
    "Mauv",
    "Yellow",
    "Pink",
    "Purple",
    "Khaki",
    "Aquamarine",
    "Green",
    "Blue",
    "Crimson"
];