export interface Car {
    id: number,
    brand: string,
    model: string,
    km: string,
    year: string,
    shift: string,
    fuel: string,
    color: string,
    car_type: string,
    e_car: boolean,
    damages?: []
}

export const Brands: Array<string> = [
    "Acura",
    "Aston Martin",
    "Audi",
    "BMW",
    "Bentley",
    "Buick",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Citroën",
    "Daewoo",
    "Daihatsu",
    "Dodge",
    "Eagle",
    "Ferrari",
    "Ford",
    "GMC",
    "Geo",
    "Hillman",
    "Holden",
    "Honda",
    "Hummer",
    "Hyundai",
    "Infiniti",
    "Isuzu",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Lotus",
    "MINI",
    "Maserati",
    "Maybach",
    "Mazda",
    "Mercedes-Benz",
    "Mercury",
    "Mitsubishi",
    "Morgan",
    "Nissan",
    "Oldsmobile",
    "Panoz",
    "Plymouth",
    "Pontiac",
    "Porsche",
    "Ram",
    "Saab",
    "Saturn",
    "Scion",
    "Shelby",
    "Spyker",
    "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo"
];

export const Models: Array<string> = [
    "1 Series",
    "100",
    "1500",
    "1500 Club Coupe",
    "200",
    "228",
    "240SX",
    "3 Series",
    "300",
    "3000GT",
    "300D",
    "300ZX",
    "323",
    "325",
    "3500",
    "3500 Club Coupe",
    "350Z",
    "400E",
    "430",
    "430 Scuderia",
    "4Runner",
    "5 Series",
    "525",
    "530",
    "57",
    "599 GTB Fiorano",
    "6 Series",
    "612 Scaglietti",
    "62",
    "626",
    "645",
    "7 Series",
    "740",
    "850",
    "88",
    "9-3",
    "9-5",
    "900",
    "911",
    "924 S",
    "928",
    "929",
    "940",
    "944",
    "98",
    "A4",
    "A6",
    "A8",
    "Acadia",
    "Accent",
    "Acclaim",
    "Accord",
    "Aero 8",
    "Aerostar",
    "Alero",
    "Allante",
    "Alpina B7",
    "Altima",
    "Amanti",
    "Amigo",
    "Aries",
    "Armada",
    "Arnage",
    "Aspen",
    "Astro",
    "Aurora",
    "Avalanche",
    "Avalon",
    "Avenger",
    "Aveo",
    "Aviator",
    "Axiom",
    "Azera",
    "Aztek",
    "Azure",
    "B-Series",
    "B-Series Plus",
    "B2600",
    "B9 Tribeca",
    "Baja",
    "Beretta",
    "Bonneville",
    "Boxster",
    "Bravada",
    "Breeze",
    "Brooklands",
    "C30",
    "C70",
    "C8",
    "C8 Spyder",
    "CL-Class",
    "CLK-Class",
    "CLS-Class",
    "CTS",
    "CX-7",
    "CX-9",
    "Cabriolet",
    "Caliber",
    "California",
    "Camaro",
    "Camry",
    "Canyon",
    "Capri",
    "Caprice",
    "Caravan",
    "Catera",
    "Cavalier",
    "Cayenne",
    "Cayman",
    "Celica",
    "Century",
    "Challenger",
    "Chariot",
    "Cherokee",
    "Ciera",
    "Cirrus",
    "Civic",
    "Civic Si",
    "Classic",
    "Club Wagon",
    "Clubman",
    "Cobalt",
    "Commander",
    "Compass",
    "Concorde",
    "Continental",
    "Continental Flying Spur",
    "Continental GTC",
    "Contour",
    "Cooper",
    "Corolla",
    "Corsica",
    "Corvette",
    "Cougar",
    "Countach",
    "Countryman",
    "Coupe GT",
    "Crossfire",
    "Crown Victoria",
    "Cutlass",
    "Cutlass Cruiser",
    "Cutlass Supreme",
    "D150",
    "D250 Club",
    "D350 Club",
    "Daewoo Lacetti",
    "Dakota",
    "Datsun/Nissan Z-car",
    "Daytona",
    "DeVille",
    "Defender",
    "Diablo",
    "Diamante",
    "Discovery",
    "Durango",
    "E-Class",
    "E-Series",
    "E150",
    "E250",
    "ES",
    "EV1",
    "EX",
    "Eclipse",
    "Econoline E150",
    "Econoline E250",
    "Econoline E350",
    "Edge",
    "Elan",
    "Elantra",
    "Eldorado",
    "Electra",
    "Elise",
    "Endeavor",
    "Envoy",
    "Envoy XUV",
    "Eos",
    "Equator",
    "Equinox",
    "Escalade",
    "Escalade ESV",
    "Escalade EXT",
    "Escape",
    "Escort",
    "Esperante",
    "Esprit",
    "Esprit Turbo",
    "Esteem",
    "Eurovan",
    "Evora",
    "Excursion",
    "Exige",
    "Expedition",
    "Expedition EL",
    "Explorer",
    "Explorer Sport Trac",
    "Expo LRV",
    "Express 1500",
    "Express 2500",
    "Express 3500",
    "F-250 Super Duty",
    "F-Series",
    "F150",
    "F250",
    "F350",
    "F450",
    "FF",
    "FR-S",
    "FX",
    "Familia",
    "Festiva",
    "Fiero",
    "Firebird",
    "Firefly",
    "Fit",
    "Fleetwood",
    "Focus",
    "Forester",
    "Forte",
    "Fox",
    "Freestyle",
    "Frontier",
    "Fusion",
    "G",
    "G-Class",
    "G-Series 3500",
    "G-Series G20",
    "G37",
    "GLI",
    "GS",
    "GT350",
    "GT500",
    "GTI",
    "GTO",
    "GX",
    "Galant",
    "Gallardo",
    "Genesis Coupe",
    "Golf",
    "Grand Am",
    "Grand Caravan",
    "Grand Cherokee",
    "Grand Prix",
    "Grand Prix Turbo",
    "Grand Voyager",
    "H2",
    "Highlander",
    "Hombre",
    "I",
    "IS",
    "IS F",
    "Impala",
    "Imperial",
    "Impreza",
    "Impreza WRX",
    "Integra",
    "Intrepid",
    "Ion",
    "J",
    "JUKE",
    "JX",
    "Jetta",
    "Jetta III",
    "Jimmy",
    "Journey",
    "Justy",
    "Karif",
    "L-Series",
    "L300",
    "LS",
    "LTD",
    "LTD Crown Victoria",
    "LUV",
    "LX",
    "Lancer",
    "Lancer Evolution",
    "Lanos",
    "Laser",
    "LeMans",
    "Legacy",
    "Legend",
    "Leone",
    "Liberty",
    "Lucerne",
    "Lumina",
    "Lynx",
    "M",
    "M-Class",
    "M5",
    "M6",
    "MDX",
    "MKS",
    "MKX",
    "MPV",
    "MR2",
    "MX-5",
    "MX-6",
    "Malibu",
    "Mark LT",
    "Mark VIII",
    "Marquis",
    "Matrix",
    "Maxima",
    "Mazda5",
    "Millenia",
    "Minx Magnificent",
    "Mirage",
    "Model S",
    "Monte Carlo",
    "Monterey",
    "Montero",
    "Montero Sport",
    "Mountaineer",
    "Murano",
    "Murciélago LP640",
    "Mustang",
    "NSX",
    "Navajo",
    "Navigator",
    "Neon",
    "New Beetle",
    "Oasis",
    "Odyssey",
    "Optima",
    "Outback",
    "Outlander",
    "PT Cruiser",
    "Panamera",
    "Park Avenue",
    "Paseo",
    "Passat",
    "Passport",
    "Pathfinder",
    "Precis",
    "Prius",
    "Prizm",
    "Probe",
    "Q",
    "Q7",
    "QX",
    "Quattroporte",
    "Quest",
    "R-Class",
    "RAV4",
    "RL",
    "RS 4",
    "RSX",
    "RX",
    "RX Hybrid",
    "RX-7",
    "Raider",
    "Rainier",
    "Rally Wagon 1500",
    "Ram 1500",
    "Ram 1500 Club",
    "Ram 2500",
    "Ram 3500",
    "Ram Van 1500",
    "Ram Van 3500",
    "Range Rover",
    "Ranger",
    "Rapide",
    "Regal",
    "Relay",
    "Reno",
    "Ridgeline",
    "Rio",
    "Riviera",
    "Roadmaster",
    "Rocky",
    "Rodeo",
    "Rodeo Sport",
    "Rogue",
    "S-Class",
    "S-Type",
    "S4",
    "S40",
    "S6",
    "S60",
    "S8",
    "SC",
    "SJ 410",
    "SL-Class",
    "SLK-Class",
    "SLS AMG",
    "SM",
    "SRX",
    "STS",
    "SVX",
    "Safari",
    "Savana",
    "Savana 1500",
    "Savana 2500",
    "Savana 3500",
    "Scoupe",
    "Sebring",
    "Sedona",
    "Sephia",
    "Sequoia",
    "Seville",
    "Sidekick",
    "Sienna",
    "Sierra 3500",
    "Silhouette",
    "Silverado 1500",
    "Silverado 2500",
    "Silverado 3500",
    "Silverado 3500HD",
    "Skyhawk",
    "Skylark",
    "Solara",
    "Sonata",
    "Sonoma",
    "Sonoma Club",
    "Sorento",
    "Soul",
    "Space",
    "Spectra",
    "Sportage",
    "Sportvan G10",
    "Sportvan G20",
    "Sprinter",
    "Starion",
    "Stylus",
    "Suburban",
    "Suburban 1500",
    "Suburban 2500",
    "Sunbird",
    "Sunfire",
    "Swift",
    "T100 Xtra",
    "TL",
    "TT",
    "Tacoma",
    "Tacoma Xtra",
    "Tahoe",
    "Talon",
    "Taurus",
    "Tempest",
    "Tempo",
    "Tercel",
    "Tiburon",
    "Tiguan",
    "Topaz",
    "Torrent",
    "Touareg",
    "Town & Country",
    "Town Car",
    "Tracer",
    "Tracker",
    "Tredia",
    "Tribute",
    "Trooper",
    "Truck",
    "Tundra",
    "V40",
    "V70",
    "VS Commodore",
    "VUE",
    "Vandura 1500",
    "Vandura 3500",
    "Vanquish S",
    "Venture",
    "Venza",
    "Verano",
    "Verona",
    "Versa",
    "Vibe",
    "Virage",
    "Vitara",
    "Voyager",
    "Windstar",
    "Wrangler",
    "X-Type",
    "X3",
    "X5",
    "X6 M",
    "XC70",
    "XC90",
    "XF",
    "XG350",
    "XJ",
    "XK Series",
    "XL-7",
    "XLR",
    "XT",
    "Xterra",
    "Xtra",
    "Yukon",
    "Yukon XL 1500",
    "Yukon XL 2500",
    "Z3",
    "Z4 M",
    "Z8",
    "ZDX",
    "i-Series",
    "rio",
    "riolet",
    "tC"
];

export const Fuels: Array<string> = [
    "Benzin",
    "CNG",
    "Diesel",
    "Petrol",
    "Propane"
];

export const CarType: Array<string> = [
    'Automatic',
    'Manual'
];

export const Color: Array<string> = [
    "Aquamarine",
    "Blue",
    "Crimson",
    "Fuscia",
    "Goldenrod",
    "Green",
    "Indigo",
    "Khaki",
    "Maroon",
    "Mauv",
    "Orange",
    "Pink",
    "Puce",
    "Purple",
    "Red",
    "Teal",
    "Turquoise",
    "Violet",
    "Yellow"
];